### ISSUE TITLE
[BAD] Scope/Redesign?

### ISSUE THREAD

**Issue by yatil** [w3c/wai-bad-demo#4]
* A redesign, even “just” coding it responsively, would likely affect most content of the Before After Demo.
* Using the new W3C/WAI layout is probably not a good idea so people don’t get confused.
* The current [BAD already](https://www.w3.org/WAI/demos/bad/after/reports/home.html) already has links to the techniques. I wonder why they need to change to point to the Quickref which then points to techniques.
* I fully support material on how to use BAD in classrooms and other learning environments.

**Comment by brewerj** [comment]
It's expected that the recoding would trigger the need for content changes. I think that the question is, is there a way to scope that realistically without having to update every aspect of the code and content in the current cycle of work. I'd be interested in your and other people's thoughts on preventing scope creep. 

The suggestion is specifically to use some aspects of the proposed new visual design, swapping the balance of accent colors as well as other elements, at least as a jump start for an updated design for the BAD Demo. Additional design guidance would be sought beyond that but resources would be concentrated on the other aspects of the update. The actual layout of the BAD Design may be difficult to significantly change as it is optimized to show many layers of original content, annotations, etc.

The current BAD Demo has outbound links to the techniques, but inbound links from related resources to relevant info in the BAD Demo could be expanded greatly. Existing and new frag ids could be indexed and cross-linked to surface more detail about related resources and enable more cross-document linking  between different flavors of supporting material. on the same topics.

Glad that the instructional usage outline came across well.

**Comment by bakkenb** [comment]
Agree with the idea on NOT using the new WAI Site redesign colors and design. I think it would be okay to use something similar for the "Before" and "After" pages, but would like to really have a BAD site that "looks" different than the WAI site so that people have a very clear indication that they are in the BAD site.
