### ISSUE TITLE
[BAD4Curriculum] 

### ISSUE THREAD

**Issue by yatil** [w3c/wai-bad-demo#5]
* Overall like the approach
* Should have a quick entry for teachers: What can my students learn? What support material is available?
* I’d like to suggest to provide sample slides for teachers to use.

**Comment by brewerj** [comment]
Good suggestion for quick entry for teachers. Will add.

Sample slides might be ambitious but let's see.

**Comment by bakkenb** [comment]
I really like the idea of the entry point for teachers. Maybe even a suggested outline of talking points or "instructional walkthrough" of the site.

This outline could then be used to create slides. 

In general, I like the idea of providing a bit of guidance and documentation for instructors to take and edit for their own purposes. We have people in the group who have used the site instructionally. I am sure they would have ideas of what type of information/documentation/slides would be helpful.

I like the direction this is going.
